version: "3.8"

services:
  database:
    image: mysql:8.0.26
    container_name: test-db
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - 33060:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      timeout: 20s
      retries: 10
      interval: 5s

  app:
    container_name: test-app
    build:
      context: .
    entrypoint: ["npm", "run", "test"]
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data: {}
